services:
  app:
    build: .
    container_name: rag_app
    volumes:
      - .:/app
    networks:
      - ollama_ollama-network
    env_file: .env

networks:
  ollama_ollama-network:
    external: true