services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - ollama-network
    # gpu support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
  app:
    build: .
    entrypoint: "tail -f /dev/null"
    container_name: rag_app
    networks:
      - ollama-network
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    depends_on:
      - ollama

networks:
  ollama-network:
    driver: bridge