services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge